// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(config) {
    return config.set({
      basePath: '',
      frameworks: ['jasmine'],
      files: ['public/javascripts/vendor/jquery-1.10.2.min.js', 'public/javascripts/vendor/angularjs/angular.min.js', 'public/javascripts/vendor/angularjs/angular-route.min.js', 'public/javascripts/vendor/angularjs/angular-ui-router.js', 'public/javascripts/vendor/**/*.js', 'app/assets/scripts/main.coffee', 'app/assets/scripts/services/kgNewsService.coffee', 'app/assets/scripts/controllers/*.coffee', 'app/assets/scripts/admin.coffee', 'app/assets/scripts/services/admin*.coffee', 'app/assets/scripts/directives/*.coffee', 'test/assets/config/jasmine-jquery.js', 'test/assets/config/angular-mocks.js', 'test/spec/**/*.coffee'],
      preprocessors: {
        '**/*.coffee': 'coffee'
      },
      exclude: [],
      reporters: ['progress'],
      port: 9876,
      colors: true,
      logLevel: config.LOG_INFO,
      autoWatch: true,
      browsers: ['Chrome'],
      captureTimeout: 60000,
      singleRun: false
    });
  };

}).call(this);
