// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: adminNewsService', function() {
    var adminNewsService;
    beforeEach(module('kulebaoAdmin'));
    adminNewsService = {};
    beforeEach(inject(function(_adminNewsService_) {
      return adminNewsService = _adminNewsService_;
    }));
    return it('should do something', function() {
      return expect(!!adminNewsService).toBe(true);
    });
  });

}).call(this);
