// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: Adminnewsservice', function() {
    var Adminnewsservice;
    beforeEach(module('kulebaoApp'));
    Adminnewsservice = {};
    beforeEach(inject(function(_Adminnewsservice_) {
      return Adminnewsservice = _Adminnewsservice_;
    }));
    return it('should do something', function() {
      return expect(!!Adminnewsservice).toBe(true);
    });
  });

}).call(this);
