// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: newsService', function() {
    var newsService;
    beforeEach(module('app'));
    newsService = {};
    beforeEach(inject(function(_newsService_) {
      return newsService = _newsService_;
    }));
    return it('should do something', function() {
      return expect(!!newsService).toBe(true);
    });
  });

}).call(this);
