// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: Newsservice', function() {
    var Newsservice;
    beforeEach(module('kulebaoApp'));
    Newsservice = {};
    beforeEach(inject(function(_Newsservice_) {
      return Newsservice = _Newsservice_;
    }));
    return it('should do something', function() {
      return expect(!!Newsservice).toBe(true);
    });
  });

}).call(this);
