// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: ngTarget', function() {
    var scope;
    beforeEach(module('kulebaoAdmin'));
    scope = {};
    beforeEach(inject(function($rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should build up complex html', inject(function($rootScope, $compile) {
      var element1, element2, parent;
      element1 = $compile('<textarea class="target" x-ng-target="target"></textarea>')($rootScope);
      element2 = $compile('<button class="button" ng-click="target.focus()"></button>')($rootScope);
      parent = $compile('<div></div>')($rootScope);
      parent.append(element1);
      parent.append(element2);
      $rootScope.$digest();
      return parent.find(".button").click();
    }));
  });

}).call(this);
