// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: ngTarget', function() {
    var scope;
    beforeEach(module('app'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<ng-target></ng-target>');
      return element = $compile(element)(scope);
    }));
  });

}).call(this);
