// Generated by CoffeeScript 1.6.3
(function() {
  describe('app', function() {
    beforeEach(module('app'));
    return describe('KindergartenCtrl', function() {
      return it('should be working', function() {
        return expect(1 + 1).toBe(2);
      });
    });
  });

}).call(this);
