// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: NewsCtrl', function() {
    var $httpBackend, NewsCtrl;
    beforeEach(module('app'));
    NewsCtrl = {};
    $httpBackend = {};
    beforeEach(inject(function($controller, $rootScope, _$httpBackend_) {
      $httpBackend = _$httpBackend_;
      $httpBackend.expectPOST('/kindergarten/school23/parent/1/news/999').respond({
        id: 999,
        k_id: 1,
        parent_id: 1,
        news_id: 2,
        readTime: '1990-10-01'
      });
      $httpBackend.expectGET('/kindergarten/school23/news/999').respond({
        id: 999,
        k_id: 1,
        parent_id: 1,
        news_id: 1,
        readTime: '1990-10-01'
      });
      return NewsCtrl = $controller('NewsCtrl', {
        $stateParams: {
          news: 999
        }
      });
    }));
    return it('should have 2 news from request', function() {
      $httpBackend.flush();
      return expect(NewsCtrl.news.id).toBe(999);
    });
  });

}).call(this);
