// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: NewsCtrl', function() {
    var NewscontrollerCtrl, scope;
    beforeEach(module('app'));
    NewscontrollerCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return NewscontrollerCtrl = $controller('NewsCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);
