// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: WipcontrollerCtrl', function() {
    var WipcontrollerCtrl, scope;
    beforeEach(module('app'));
    WipcontrollerCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return WipcontrollerCtrl = $controller('WipCtrl', {
        $scope: scope
      });
    }));
    return it('should clean tab name', function() {
      return expect(scope.tabName).toBe('wip');
    });
  });

}).call(this);
